/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `eclipse`
}

group="org.qommons"
version="2.0.0"
description = "Many general utility and useful APIs"


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

java {                                      
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
	implementation("javax.servlet:javax.servlet-api:4.0.1")
	implementation("com.hierynomus:sshj:0.35.0")

    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")
}
