package org.qommons;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Random;
import java.util.function.Consumer;
import java.util.regex.Pattern;

import org.qommons.ArgumentParsing.ArgumentParser;
import org.qommons.ArgumentParsing.Arguments;
import org.qommons.io.Format;

/**
 * <p>
 * This class may be used by test classes to generate pseudo-random numbers that would be used to generate pseudo-random test cases. These
 * test class would attempt to use the randomness to cover every possible permutation of code invocation in order to test a system
 * more-or-less completely.
 * </p>
 *
 * <p>
 * For example, to test a stateful class with 3 methods, a(int arg), b(boolean arg), and c(double arg), the class could do something like
 *
 * <pre>
 * (TestHelper helper) -> {
 * 	ToTest test = new ToTest();
 * 	int tries = 5000;
 * 	for (int i = 0; i &lt; tries; i++) {
 * 		switch (helper.getInt(0, 3)) {
 * 		case 0:
 * 			int intArg = helper.getInt(-1, 1000000); // Constrain to the expected argument range of method a()
 * 			assertOutputOfACorrect(intArg, a(intArg));
 * 			break;
 * 		case 1:
 * 			boolean boolArg = helper.getBoolean();
 * 			assertOutputOfBCorrect(boolArg, b(boolArg));
 * 			break;
 * 		case 2:
 * 			double doubleArg = helper.getDouble();
 * 			assertOutputOfCCorrect(doubleArg, C(doubleArg));
 * 			break;
 * 		}
 * 	}
 * }
 * </pre>
 *
 * This would generate 5000 random states in the tested class for each test case.
 * </p>
 * <p>
 * Far more than just a utility wrapper around {@link Random}, this class may be used to generate unlimited test cases that can be run
 * ad-infinitum. It keeps track of the history of each test case. It has several modes:
 * <ul>
 * <li><b>--random</b> In this mode, random test cases are generated and failures are logged for later reproduction. Options::
 * <ul>
 * <li><b>--max-cases=&lt;integer&gt;</b> The maximum number of test cases to run.</li>
 * <li><b>--max-time=&lt;duration&gt;</b> The maximum amount of time to run.</li>
 * <li><b>--max-failures=&lt;integer&gt;</b> The maximum number of failures to encounter.</li>
 * <li><b>--only-new=&lt;boolean&gt;</b> If true, this class will not re-attempt test cases that were last known to be broken. Default is
 * true.</li>
 * </ul>
 * </li>
 * <li><b>--reproduce</b> In this mode, tests that have broken recently are re-run. Options:
 * <ul>
 * <li><b>--debug</b> If this flag is set, the helper will invoke a break point (via {@link org.qommons.BreakpointHere}) just before the
 * most recent point of failure for each test.</li>
 * <li><b>--hash=&lt;debug-hash&gt;</b> The hash or comma-separated hashes to re-execute. If unspecified, all test cases that were last
 * known to be broken will be run.</li>
 * <li><b>--debug-at=&lt;long integer&gt;</b> The number of bytes in the test case at which to catch a breakpoint. Must be used with -hash
 * for a single hash.</li>
 * </ul>
 * </li>
 * </ul>
 * All modes have the following options:
 * <ul>
 * <li><b>--test-class=&lt;qualified.className&gt;</b> The {@link Testable} class to test. Must have a no-argument constructor.</li>
 * <li><b>--hold-time=&lt;duration&gt;</b> The maximum time to wait between invocations to this helper (if unspecified by execution) before
 * failure is assumed.</li>
 * </ul>
 * </p>
 * <p>
 * The console output of this class can be used to monitor the progress of the test. When each test case is started, the hash for that test
 * is printed immediately. When the test case finishes successfully, SUCCESS is printed, followed by the percent success for the current
 * testing session. Upon failure, FAILURE or TIMEOUT is printed, followed by "@" and the number of bytes generated by the helper for the
 * test case before its failure. This may be used (in conjunction with the -hash argument) in -reproduce mode with the -debug-at argument to
 * invoke a break point just prior to the failure. Then the stack trace of the exception or of the execution upon timeout is printed.
 * </p>
 */
public class TestHelper {
	public static interface Testable extends Consumer<TestHelper> {}

	public static class TestFailure {
		public final long seed;
		public final long placemark;

		public TestFailure(long seed, long placemark) {
			this.seed = seed;
			this.placemark = placemark;
		}
	}

	private final long theSeed;
	private final Random theRandomness;
	private long theBytes;
	private long theLastPlacemark;
	private long theBreak;

	private TestHelper() {
		this(Double.doubleToLongBits(Math.random()), 0, -1);
	}

	private TestHelper(long seed, long bytes, long breakPoint) {
		theSeed=seed;
		theRandomness=new Random(seed);
		while (theBytes < bytes - 7)
			getAnyLong();
		while (theBytes < bytes)
			getBoolean();
		theLastPlacemark = -1;
		theBreak = breakPoint < 0 ? Long.MAX_VALUE : breakPoint;
	}

	private void getBytes(int bytes) {
		boolean postBreak = theBytes >= theBreak;
		theBytes += bytes;
		if (!postBreak && theBytes >= theBreak)
			BreakpointHere.breakpoint();
	}

	public long getSeed() {
		return theSeed;
	}

	public long getPosition() {
		return theBytes;
	}

	public long getLastPlacemark() {
		return theLastPlacemark;
	}

	public TestHelper fork() {
		long forkSeed = getAnyLong();
		return new TestHelper(forkSeed, 0, -1);
	}

	public void placemark() {
		getBoolean();
		theLastPlacemark = theBytes;
	}

	public TestHelper tolerate(Duration timeout) {
		return this;
	}

	public int getAnyInt() {
		getBytes(4);
		return theRandomness.nextInt();
	}

	public int getInt(int min, int max) {
		if (min == max)
			return min;
		return min + Math.abs(getAnyInt() % (max - min));
	}

	public long getAnyLong() {
		getBytes(8);
		return theRandomness.nextLong();
	}

	public long getLong(long min, long max) {
		return min + Math.abs(getAnyLong() % (max - min));
	}

	public double getDouble() {
		getBytes(8);
		return theRandomness.nextDouble();
	}

	public double getGaussian() {
		getBytes(8);
		return theRandomness.nextGaussian();
	}

	public double getAnyDouble() {
		return Double.longBitsToDouble(getAnyLong());
	}

	public double getDouble(double min, double max) {
		return min + getDouble() * (max - min);
	}

	public boolean getBoolean() {
		getBytes(1);
		byte[] bytes = new byte[1];
		theRandomness.nextBytes(bytes);
		return bytes[0] >= 0;
	}

	public boolean getBoolean(double odds) {
		return getDouble() < odds;
	}

	public static void main(String[] args) {
		ArgumentParser parser = new ArgumentParser()//
			.forDefaultFlagPattern()//
			/**/.flagArg("random").requiredIfNot("reproduce").requiresNot("reproduce")//
			/**/.flagArg("reproduce").requiredIfNot("random").requiresNot("random")//
			/**/.flagArg("debug").requires("reproduce")//
			/**/
			.forDefaultPattern()//
			/**/.stringArg("test-class").required()//
			/**/.durationArg("hold-time").defValue(Duration.ofSeconds(60))//
			/**/.intArg("max-cases").requires("random").atLeast(1)//
			/**/.durationArg("max-time").requires("random")//
			/**/.intArg("max-failures").requires("random").atLeast(1)//
			/**/.booleanArg("only-new").requires("random").defValue(true)//
			/**/.intArg("debug-at").requires("random").atLeast(0)//
			.forDefaultMultiValuePattern()//
			/**/.patternArg("hash", Pattern.compile("[0-9a-fA-F]{16}"))//
			.getParser();
		Arguments parsed = parser.parse(args);
		Class<? extends Testable> testable;
		try {
			testable = Class.forName(parsed.getString("test-class")).asSubclass(Testable.class);
		} catch (ClassNotFoundException e) {
			System.err.println("Test class " + parsed.getString("test-class") + " not found");
			e.printStackTrace();
			return;
		} catch (ClassCastException e) {
			System.err.println("Test class " + parsed.getString("test-class") + " is not " + Testable.class.getName());
			return;
		}
		Constructor<? extends Testable> creator = getCreator(testable);

		/* TODO Append broken test cases to a file. Remove fixed test cases.
		 * Attempt to co-locate this file with the class being tested.
		 * If co-located, the file should be the simple name of the class.broken.
		 * Otherwise make a sub-dir called testhelper under the current working dir and
		 * put the file in there, named fully.qualified.ClassName.broken. */
		if (parsed.hasFlag("random")) {
			testRandom(testable, false, //
				(int) parsed.getInt("max-cases", Integer.MAX_VALUE), //
				(int) parsed.getInt("max-failures", Integer.MAX_VALUE), //
				parsed.getDuration("max-time", null), true, true, false);
		} else {
			long debugAt = parsed.get("debug-at") != null ? parsed.getLong("debug-at") : -1;
			int i = 0;
			for (String hash : parsed.getAll("hash", String.class))
				doTest(creator, new TestHelper(Long.parseLong(hash, 16), 0, debugAt), ++i, true, true);
		}
	}

	public static int testRandom(Class<? extends Testable> testable, boolean knownFailuresFirst, int maxCases, int maxFailures,
		Duration maxTime, boolean printProgress, boolean printFalures, boolean throwOnFailure) throws AssertionError {
		Constructor<? extends Testable> creator = getCreator(testable);
		if (maxCases <= 0)
			maxCases = Integer.MAX_VALUE;
		if (maxFailures <= 0)
			maxFailures = Integer.MAX_VALUE;
		Instant termination = maxTime == null ? Instant.MAX : Instant.now().plus(maxTime);
		int failures = 0;
		Throwable firstError = null;
		if (knownFailuresFirst) {
			List<TestFailure> knownFailures = getKnownFailures(testable);
			if (knownFailures != null && !knownFailures.isEmpty()) {

			}
		}
		for (int i = 0; i < maxCases && failures < maxFailures && Instant.now().compareTo(termination) < 0; i++) {
			Throwable err = doTest(creator, new TestHelper(), i + 1, printProgress, printFalures);
			if (err != null) {
				if (firstError == null)
					firstError = err;
				failures++;
			}
		}
		if (throwOnFailure && failures > 0) {
			if (firstError instanceof AssertionError)
				throw (AssertionError) firstError;
			throw new AssertionError(firstError.getMessage(), firstError);
		}
		return failures;
	}

	public static Throwable testReproduce(Class<? extends Testable> testable, String hash, long debugAt, boolean printProgress,
		boolean printFailures, boolean throwOnFailure) throws AssertionError {
		Throwable err = doTest(getCreator(testable), new TestHelper(Long.parseLong(hash, 16), 0, debugAt), -1, printProgress,
			printFailures);
		if (throwOnFailure && err != null) {
			if (err instanceof AssertionError)
				throw (AssertionError) err;
			throw new AssertionError(err.getMessage(), err);
		}
		return err;
	}

	public static void testSingle(Testable testable, long hash, long debugAt) throws AssertionError {
		TestHelper helper = new TestHelper(hash, 0, debugAt);
		Throwable err = doTest(testable, helper, -1, false, false);
		if (err != null) {
			StringBuilder msg = new StringBuilder(Long.toHexString(hash)).append('@').append(helper.getPosition());
			if (helper.getLastPlacemark() >= 0)
				msg.append("(placemark@").append(helper.getLastPlacemark()).append(") ");
			msg.append(err.getMessage());
			throw new AssertionError(msg.toString(), err);
		}
	}

	private static List<TestFailure> getKnownFailures(Class<? extends Testable> testable) {
		// TODO
	}

	private static <T extends Testable> Constructor<T> getCreator(Class<T> testable) {
		Constructor<T> creator;
		try {
			try {
				creator = testable.getConstructor();
			} catch (NoSuchMethodException e) {
				creator = testable.getDeclaredConstructor();
			}
		} catch (NoSuchMethodException | SecurityException e) {
			throw new IllegalStateException("Test class " + testable.getName() + " does not have a no-argument constructor", e);
		}
		if (!creator.isAccessible()) {
			try {
				creator.setAccessible(true);
			} catch (SecurityException e) {
				throw new IllegalStateException(
					"No-argument constructor for test class " + testable.getName() + " is not accessible (try making it public)", e);
			}
		}
		return creator;
	}

	private static Throwable doTest(Constructor<? extends Testable> creator, TestHelper testHelper, int caseNumber,
		boolean printProgress, boolean printFailures) {
		Testable tester;
		try {
			tester = creator.newInstance();
		} catch (InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException e) {
			throw new IllegalStateException("Could not instantiate tester " + creator.getDeclaringClass().getName(), e);
		}
		return doTest(tester, testHelper, caseNumber, printProgress, printFailures);
	}

	private static Throwable doTest(Testable tester, TestHelper testHelper, int caseNumber, boolean printProgress, boolean printFailures) {
		String caseLabel = "";
		if (caseNumber > 0)
			caseLabel += "[" + caseNumber + "] ";
		caseLabel += Long.toHexString(testHelper.getSeed()).toUpperCase() + ": ";
		if (printProgress) {
			System.out.print(caseLabel);
			System.out.flush();
		}
		long start = System.nanoTime();
		try {
			tester.accept(testHelper);
			if (printProgress)
				System.out.println("SUCCESS in " + Format.durationFormat().format(Duration.ofNanos(System.nanoTime() - start)));
			return null;
		} catch (Throwable e) {
			if (printProgress || printFailures) {
				if (!printProgress)
					System.err.print(caseLabel);
				StringBuilder msg = new StringBuilder();
				msg.append("FAILURE@").append(testHelper.getPosition()).append(" in ");
				Format.durationFormat().append(msg, Duration.ofNanos(System.nanoTime() - start));
				long placemark = testHelper.getLastPlacemark();
				if (placemark >= 0)
					msg.append("\nPlacemark@").append(placemark);
				System.err.println(msg);
				e.printStackTrace();
			}
			return e;
		}
	}
}
